// Generated by https://quicktype.io

import {SetStateAction, Dispatch} from 'react';

export interface LoginResponse {
  usuario: Usuario;
  token: string;
}

export interface Usuario {
  rol: string;
  estado: boolean;
  google: boolean;
  nombre: string;
  correo: string;
  uid: string;
  img?: string;
}

export interface LoginData {
  correo: string;
  password: string;
  loading: Dispatch<SetStateAction<boolean>>;
}

export interface RegisterData {
  nombre: string;
  correo: string;
  password: string;
  loading: Dispatch<SetStateAction<boolean>>;
}

// Productos

// Generated by https://quicktype.io

export interface ProductsResponse {
  total: number;
  productos: Producto[];
}

export interface Producto {
  precio: number;
  _id: string;
  nombre: string;
  descripcion: string;
  img?: string;
  categoria: Categoria;
  usuario: Categoria;
  disponible?: boolean;
}

/* export interface Categoria {
  _id: string;
  nombre: string;
} */

/* Categorias */
// Generated by https://quicktype.io

export interface CategoriesResponse {
  total: number;
  categorias: Categoria[];
}

export interface Categoria {
  _id: string;
  nombre: string;
  usuario?: CategoriaUsuario;
}

export interface CategoriaUsuario {
  _id: string;
  nombre: string;
}

/* Search */
// Generated by https://quicktype.io

export interface SearchResponse {
  results: SearchResult[];
}

export interface SearchResult {
  precio: number;
  _id: string;
  nombre: string;
  descripcion: string;
  img: string;
  categoria: CategoriaUsuario;
  usuario: string;
}

/* export interface Categoria {
  _id:    string;
  nombre: string;
} */
